{% set name = "poco" %}
{% set version = "1.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pocoproject.org/releases/{{ name }}-{{ version }}/{{ name }}-{{ version }}-all.tar.gz
  sha256: 514392c63d29d5d524b9a6b3994a92c17d7db6163d60ff18f7751308d9de2da1

build:
  number: 0
  # poco is quite bad at ABI stability: https://abi-laboratory.pro/index.php?view=timeline&l=poco
  run_exports:
    - {{ pin_subpackage("poco", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openssl
    - unixodbc  # [not win]
  run:
    - openssl
    - unixodbc  # [not win]

test:
  commands:
    - test -f ${PREFIX}/lib/libPocoNet${SHLIB_EXT}  # [unix]
    - test ! -f ${PREFIX}/lib/libPocoNet.a  # [unix]
    - if not exist %LIBRARY_BIN%\PocoNet%SHLIB_EXT% exit 1  # [win]

about:
  home: https://github.com/pocoproject/poco
  license: BSL-1.0
  license_family: OTHER
  license_file: LICENSE
  summary: powerful cross-platform C++ libraries for building network- and internet-based applications

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
