{% set name = "poco" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pocoproject.org/releases/{{ name }}-{{ version }}/{{ name }}-{{ version }}-all.tar.gz
  sha256: 0387bf0f9d313e2311742e1ad0b64e07f2f3e76039eed20e3b9aa9951b88e187

build:
  number: 2002

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openssl
    - unixodbc  # [not win]
  run:
    - openssl
    - unixodbc  # [not win]

test:
  commands:
    - test -f ${PREFIX}/lib/libPocoNet${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\PocoNet%SHLIB_EXT% exit 1  # [win]

about:
  home: https://github.com/pocoproject/poco
  license: Boost-1.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'powerful cross-platform C++ libraries for building network- and internet-based applications'

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
