appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: df4VCWk918r1NGcbjLIlAEuIHXT+5DbheaSUFHZi4u+bKi/gD0FUz6y03rwv8M1vOtrTA+dX9mqGDkApD/vbjwkkUbSLb6CQHqWY4HgtmL7m2C29OBHbFAZ78HyPxuODYGgSc5yWhkUXX6k4B4SaFWuc1Cap/RbRJP43+CFUMf56xI2JzGxiBCjQiZUuZkZ7e1km0fWIwvOuy5RZBsg5zUB+F2bmOT8CBVeMFAoC0d64CGqIDzcOiFKhKYgetikYlYqpCPtogCjQSCE8vFAdWo4YpykEhbLszxb1zePhMQW3ZOIBibXguWE072ZkEKQBXHmM4SGOETTTrgs83CT1XdIfp+cGQUp/KdyMe+4DI6ROIntid2D9LfGClCjF53bqwegBgWTftEM7mqM4CANf5tRfPxiNvRbHsKxPrc/1x9wP5I+XEphxKreZgb8gNWb1TRIzkZi4GslxqtQe24eZQ5ks845/MQJta5AYyQ4+B3MfNF8fJ0DlzjZd+HTu3G+YxE/T8iLSAAj6zIZwxg++EXO0MrkucNK/b+WmT2G/rS65z0+3z5HJq534gbURspGvtw6H5xR3KDj/6lg0ufa88fdXWihs5ktP0r5m8vZi28K0WhIC4KZ1yToUT5gDFRlxU2wn+1KGkvCNmjE1ntSUyDhz6uT0oSClI6xa+h3hs9Y=}
provider:
  win: appveyor
